"""init core schema

Revision ID: dd5ac2a49170
Revises: 
Create Date: 2026-04-06 20:45:59.155030
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'dd5ac2a49170'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_masked', sa.String(length=255), nullable=True),
    sa.Column('scene_type', sa.String(length=40), server_default=sa.text("'GENERAL'"), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configs')),
    sa.UniqueConstraint('provider_code', 'model_name', name=op.f('uq_model_configs_provider_code'))
    )
    op.create_index(op.f('ix_model_configs_provider_code'), 'model_configs', ['provider_code'], unique=False)
    op.create_table('roles',
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=True)
    op.create_table('source_configs',
    sa.Column('source_code', sa.String(length=80), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('authority_level', sa.String(length=20), server_default=sa.text("'MEDIUM'"), nullable=False),
    sa.Column('priority_weight', sa.Numeric(precision=6, scale=2), server_default=sa.text('1.00'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_configs'))
    )
    op.create_index(op.f('ix_source_configs_object_type'), 'source_configs', ['object_type'], unique=False)
    op.create_index(op.f('ix_source_configs_source_code'), 'source_configs', ['source_code'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('action_detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('research_tasks',
    sa.Column('task_no', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('task_title', sa.String(length=255), nullable=False),
    sa.Column('research_goal', sa.Text(), nullable=True),
    sa.Column('time_range', sa.String(length=100), nullable=True),
    sa.Column('selected_model_id', sa.BigInteger(), nullable=True),
    sa.Column('source_strategy', sa.String(length=100), nullable=True),
    sa.Column('task_params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('current_stage', sa.String(length=50), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('progress_percent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_model_id'], ['model_configs.id'], name=op.f('fk_research_tasks_selected_model_id_model_configs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_research_tasks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_tasks'))
    )
    op.create_index(op.f('ix_research_tasks_object_type'), 'research_tasks', ['object_type'], unique=False)
    op.create_index(op.f('ix_research_tasks_selected_model_id'), 'research_tasks', ['selected_model_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_status'), 'research_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_research_tasks_task_no'), 'research_tasks', ['task_no'], unique=True)
    op.create_index(op.f('ix_research_tasks_user_id'), 'research_tasks', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id'))
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('model_config_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('opportunities', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('structured_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], name=op.f('fk_analysis_results_model_config_id_model_configs')),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name=op.f('fk_analysis_results_task_id_research_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results'))
    )
    op.create_index(op.f('ix_analysis_results_model_config_id'), 'analysis_results', ['model_config_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_task_id'), 'analysis_results', ['task_id'], unique=False)
    op.create_table('materials',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('source_config_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('authority_level', sa.String(length=20), server_default=sa.text("'MEDIUM'"), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('is_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_config_id'], ['source_configs.id'], name=op.f('fk_materials_source_config_id_source_configs')),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name=op.f('fk_materials_task_id_research_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_index(op.f('ix_materials_dedup_key'), 'materials', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_materials_source_config_id'), 'materials', ['source_config_id'], unique=False)
    op.create_index(op.f('ix_materials_task_id'), 'materials', ['task_id'], unique=False)
    op.create_table('reports',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.String(length=20), server_default=sa.text("'BRIEF'"), nullable=False),
    sa.Column('report_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('word_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name=op.f('fk_reports_task_id_research_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_task_id'), 'reports', ['task_id'], unique=False)
    op.create_table('task_stage_logs',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_code', sa.String(length=50), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'STARTED'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail_data', sa.JSON(), nullable=False),
    sa.Column('operator_type', sa.String(length=20), server_default=sa.text("'SYSTEM'"), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name=op.f('fk_task_stage_logs_task_id_research_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_stage_logs'))
    )
    op.create_index(op.f('ix_task_stage_logs_stage_code'), 'task_stage_logs', ['stage_code'], unique=False)
    op.create_index(op.f('ix_task_stage_logs_task_id'), 'task_stage_logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_stage_logs_task_id'), table_name='task_stage_logs')
    op.drop_index(op.f('ix_task_stage_logs_stage_code'), table_name='task_stage_logs')
    op.drop_table('task_stage_logs')
    op.drop_index(op.f('ix_reports_task_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_materials_task_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_source_config_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_dedup_key'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_analysis_results_task_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_model_config_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_research_tasks_user_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_task_no'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_status'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_selected_model_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_object_type'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_configs_source_code'), table_name='source_configs')
    op.drop_index(op.f('ix_source_configs_object_type'), table_name='source_configs')
    op.drop_table('source_configs')
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_model_configs_provider_code'), table_name='model_configs')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
